
#line 3 "lex.yy.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer yyFlexLexer

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */
#include <iostream>
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	std::streambuf* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 100
#define YY_END_OF_BUFFER 101
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[254] =
    {   0,
        0,    0,    0,    0,    0,    0,  101,   99,   97,   98,
       85,   41,   91,   84,   42,   79,   80,   89,   88,   76,
       87,   83,   90,   37,   37,   77,   73,   92,   78,   93,
       96,   34,   34,   81,   82,   94,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   74,   95,   75,   86,   44,   43,   49,   50,  100,
      100,   72,   58,   75,   67,   59,   56,   64,   54,   65,
       55,   66,    0,   39,    1,   57,   40,   36,    0,   37,
        0,   37,   82,   74,   81,   63,   69,   71,   70,   62,
       34,   41,   42,   60,   34,   34,   34,   34,   34,   34,

        9,   34,   34,   34,   34,   34,   34,   17,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   61,
       68,   48,   45,   47,   48,   51,    0,   39,   39,    0,
       40,   36,    0,   38,   35,   53,   52,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   15,   34,
       18,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   47,   46,    0,   39,
        0,   39,    0,   40,   38,   35,    2,   34,    4,    5,
       34,   34,   34,   34,   11,   12,   34,   34,   16,   19,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,

       34,   31,   34,   34,   47,   46,    0,   39,    3,    6,
       34,   34,   34,   34,   14,   34,   34,   22,   34,   34,
       34,   34,   34,   34,   29,   34,   34,   33,   34,   34,
       10,   13,   34,   21,   23,   24,   25,   26,   27,   34,
       34,   34,   34,    8,   34,   28,   34,   34,    7,   20,
       30,   32,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   26,   26,   26,   27,   28,
       29,   29,   29,   29,   29,   30,   29,   29,   29,   29,
       29,   29,   29,   29,   31,   29,   29,   32,   29,   29,
       33,   34,   35,   36,   29,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   29,   46,   47,   48,   49,
       50,   51,   29,   52,   53,   54,   55,   56,   57,   58,
       59,   60,   61,   62,   63,   64,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[65] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    2,    2,    1,
        1,    1,    1,    1,    1,    2,    2,    2,    3,    3,
        3,    3,    1,    1,    1,    1,    2,    2,    2,    2,
        2,    2,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[260] =
    {   0,
        0,    0,   62,   63,   69,   70,  395,  396,  396,  396,
      371,  396,   56,   62,  396,  396,  396,  370,   64,  396,
       67,   83,   71,   90,   93,  368,  396,   93,  368,   60,
      396,    0,   81,  396,  396,  367,  334,  336,   82,   73,
       80,   45,  337,   86,  336,  344,   89,  325,  334,  332,
      337,  396,   95,  396,  396,  396,  396,  396,  396,  136,
      138,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  365,  144,  396,  396,  148,  182,  165,  172,
        0,    0,  396,  396,  396,  356,  396,  396,  396,  355,
        0,  396,  396,  396,  323,  335,  322,  337,  324,  330,

      316,  317,  314,  314,  317,  314,  311,    0,  310,  314,
       93,  312,   99,  112,  316,  309,   99,  113,  314,  396,
      396,  396,  396,  163,    0,  396,  203,  396,  213,  230,
      396,  203,  187,  234,  235,  396,  396,  308,  320,  315,
      303,  134,  317,  315,  311,  303,  309,  312,    0,  298,
        0,  304,  301,  290,  292,  285,  292,  278,  276,  275,
      287,  277,  281,  285,  287,  276,  175,    0,  207,  250,
      277,  396,  253,  256,  396,  257,    0,  276,    0,    0,
      267,  275,  264,  270,    0,    0,  263,  260,    0,    0,
      260,  259,  256,  268,  258,  257,  254,  246,  243,  230,

      234,    0,  209,  220,  396,  396,  282,  288,    0,    0,
      210,  210,  215,  197,    0,  191,  190,    0,  198,  194,
      196,  174,  174,  175,    0,  165,  166,    0,  155,  154,
        0,    0,  166,    0,    0,    0,    0,    0,    0,  156,
      132,  122,  109,    0,   88,    0,   90,   83,    0,    0,
        0,    0,  396,  335,  337,  340,  104,   91,   86
    } ;

static const flex_int16_t yy_def[260] =
    {   0,
      253,    1,  254,  254,  254,  254,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,   24,  253,  253,  253,  253,  253,
      253,  255,  255,  253,  253,  253,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  253,  253,  253,  253,  253,  253,  253,  253,  256,
      256,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      257,   25,  253,  253,  253,  253,  253,  253,  253,  253,
      255,  253,  253,  253,  255,  255,  255,  255,  255,  255,

      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  253,
      253,  253,  253,  253,  258,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  257,  253,  253,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  253,  259,  253,  253,
      253,  253,  253,  253,  253,  253,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,

      255,  255,  255,  255,  253,  253,  253,  253,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,    0,  253,  253,  253,  253,  253,  253
    } ;

static const flex_int16_t yy_nxt[461] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   25,   26,
       27,   28,   29,   30,   31,   32,   32,   32,   32,   33,
       32,   32,   34,    8,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   32,   44,   32,   45,   32,   32,   32,
       32,   46,   47,   48,   49,   50,   51,   32,   32,   32,
       52,   53,   54,   55,   57,   57,   58,   58,   65,   59,
       59,   57,   57,   58,   58,   68,   59,   59,   63,   64,
       70,   75,   89,   90,   66,   92,   69,  206,   93,   71,
       72,  105,  168,   76,  106,   60,   60,   73,   84,   74,

       74,   74,   61,   61,   77,  135,   78,   78,   78,   82,
       82,   82,   85,  100,   86,   87,   79,  120,   97,   80,
       80,   81,  101,  252,  253,   98,  102,  108,  103,  251,
       79,   99,  112,  113,  109,  153,   80,  104,  123,  250,
      253,  156,  114,  162,   80,  115,  154,   81,  158,  249,
      253,  163,  124,  124,  124,  124,  121,  164,  157,  165,
       74,   74,   74,  159,  129,  129,  129,  125,  248,  125,
      127,  128,  247,  128,  130,  131,  133,  131,  133,  167,
      167,  134,  134,  134,  127,  128,  181,  182,  130,  131,
      128,  205,  205,  125,  131,  125,   77,  246,   78,   78,

       78,   80,   80,  134,  134,  134,  245,  244,   79,  243,
      242,  132,  132,  241,  169,  240,  169,  239,   80,  170,
      170,  170,   79,  170,  170,  170,   80,  238,  132,  129,
      129,  129,  132,  132,  237,  236,  132,  235,  234,  171,
      172,  173,  172,  173,  233,  232,  174,  174,  174,  132,
      134,  134,  134,  171,  172,  231,  230,  132,  229,  172,
      228,  175,  227,  175,  176,  176,  170,  170,  170,  174,
      174,  174,  174,  174,  174,  175,  226,  128,  225,  128,
      175,  176,  224,  131,  223,  131,  176,  176,  207,  176,
      207,  128,  222,  208,  208,  208,  128,  131,  208,  208,

      208,  221,  131,  176,  208,  208,  208,  220,  219,  218,
      217,  176,  216,  215,  214,  172,  213,  172,  212,  211,
      210,  209,  204,  203,  202,  201,  200,  199,  198,  172,
      197,  196,  195,  194,  172,   56,   56,   56,   91,   91,
      122,  122,  122,  193,  192,  191,  190,  189,  188,  187,
      186,  185,  184,  183,  180,  179,  178,  177,  166,  161,
      160,  155,  152,  151,  150,  149,  148,  147,  146,  145,
      144,  143,  142,  141,  140,  139,  138,  137,  136,  126,
      119,  118,  117,  116,  111,  110,  107,   96,   95,   94,
       88,   83,   67,   62,  253,    7,  253,  253,  253,  253,

      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253
    } ;

static const flex_int16_t yy_chk[461] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,    3,    4,   14,    3,
        4,    5,    6,    5,    6,   19,    5,    6,   13,   13,
       21,   23,   30,   30,   14,   33,   19,  259,   33,   21,
       21,   42,  258,   23,   42,    3,    4,   22,   28,   22,

       22,   22,    5,    6,   24,  257,   24,   24,   24,   25,
       25,   25,   28,   40,   28,   28,   24,   53,   39,   24,
       24,   24,   40,  248,   25,   39,   41,   44,   41,  247,
       24,   39,   47,   47,   44,  111,   24,   41,   60,  245,
       61,  113,   47,  117,   24,   47,  111,   24,  114,  243,
       25,  117,   60,   60,   61,   61,   53,  118,  113,  118,
       74,   74,   74,  114,   77,   77,   77,   60,  242,   61,
       74,   74,  241,   74,   77,   77,   79,   77,   79,  124,
      124,   79,   79,   79,   74,   74,  142,  142,   77,   77,
       74,  167,  167,   60,   77,   61,   78,  240,   78,   78,

       78,   80,   80,  133,  133,  133,  233,  230,   78,  229,
      227,   78,   78,  226,  127,  224,  127,  223,   80,  127,
      127,  127,   78,  169,  169,  169,   80,  222,   78,  129,
      129,  129,  132,  132,  221,  220,   78,  219,  217,  129,
      129,  130,  129,  130,  216,  214,  130,  130,  130,  132,
      134,  134,  134,  129,  129,  213,  212,  132,  211,  129,
      204,  134,  203,  134,  135,  135,  170,  170,  170,  173,
      173,  173,  174,  174,  174,  134,  201,  170,  200,  170,
      134,  135,  199,  174,  198,  174,  176,  176,  171,  135,
      171,  170,  197,  171,  171,  171,  170,  174,  207,  207,

      207,  196,  174,  176,  208,  208,  208,  195,  194,  193,
      192,  176,  191,  188,  187,  208,  184,  208,  183,  182,
      181,  178,  166,  165,  164,  163,  162,  161,  160,  208,
      159,  158,  157,  156,  208,  254,  254,  254,  255,  255,
      256,  256,  256,  155,  154,  153,  152,  150,  148,  147,
      146,  145,  144,  143,  141,  140,  139,  138,  119,  116,
      115,  112,  110,  109,  107,  106,  105,  104,  103,  102,
      101,  100,   99,   98,   97,   96,   95,   90,   86,   73,
       51,   50,   49,   48,   46,   45,   43,   38,   37,   36,
       29,   26,   18,   11,    7,  253,  253,  253,  253,  253,

      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "ansic.l"
#line 2 "ansic.l"
#include <stdio.h>
#include "y.tab.h"
#include<ctype.h>
#include<malloc.h>
int yylex();
void comment();
int check_type();
YYSTYPE yylval;
YYLTYPE yylloc;
/*Para el tipo del token CONSTANT*/
#define INTVAL 0
#define DOUBLEVAL 1
#define CHARVAL 2
char *buffer = NULL;
int buffer_size = 0;
#define isodigit(x) ((x) >= '0' && (x) <='7')
#define hextoint(x) (isdigit((x)) ? (x) - '0' : ((x) - 'A') + 10)
void yyerror(char *message);
#define YY_USER_ACTION {yylloc.first_column = yylloc.last_column + 1; yylloc.last_column = yylloc.first_column + yyleng - 1;}
#line 598 "lex.yy.cc"

#line 600 "lex.yy.cc"

#define INITIAL 0
#define INSTRING 1
#define INCHAR 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
\
	if ( (int)(result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
#define YY_DECL int yyFlexLexer::yylex()
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin.rdbuf(std::cin.rdbuf());

		if ( ! yyout )
			yyout.rdbuf(std::cout.rdbuf());

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 33 "ansic.l"

#line 736 "lex.yy.cc"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 254 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 396 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 34 "ansic.l"
{ comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 36 "ansic.l"
{return(AUTO); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 37 "ansic.l"
{return(BREAK); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 38 "ansic.l"
{return(CASE); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 39 "ansic.l"
{return(CHAR); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 40 "ansic.l"
{return(CONST); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 41 "ansic.l"
{return(CONTINUE); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 42 "ansic.l"
{return(DEFAULT); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 43 "ansic.l"
{return(DO); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 44 "ansic.l"
{return(DOUBLE); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 45 "ansic.l"
{return(ELSE); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 46 "ansic.l"
{return(ENUM); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 47 "ansic.l"
{return(EXTERN); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 48 "ansic.l"
{return(FLOAT); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 49 "ansic.l"
{return(FOR); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 50 "ansic.l"
{return(GOTO); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 51 "ansic.l"
{return(IF); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 52 "ansic.l"
{return(INT); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 53 "ansic.l"
{return(LONG); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 54 "ansic.l"
{return(REGISTER); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 55 "ansic.l"
{return(RETURN); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 56 "ansic.l"
{return(SHORT); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 57 "ansic.l"
{return(SIGNED); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 58 "ansic.l"
{return(SIZEOF); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 59 "ansic.l"
{return(STATIC); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 60 "ansic.l"
{return(STRUCT); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 61 "ansic.l"
{return(SWITCH); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 62 "ansic.l"
{return(TYPEDEF); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 63 "ansic.l"
{return(UNION); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 64 "ansic.l"
{return(UNSIGNED); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 65 "ansic.l"
{return(VOID); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 66 "ansic.l"
{return(VOLATILE); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 67 "ansic.l"
{return(WHILE); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 69 "ansic.l"
{   yylval.str = strdup(yytext); 
                            
                            return(check_type()); 
                        }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 74 "ansic.l"
{   yylval.val.ival = strtol(yytext,NULL,16); 
                            yylval.val.typ = INTVAL;

                            return(CONSTANT); 
                        }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 80 "ansic.l"
{   yylval.val.ival = strtol(yytext,NULL,8);
                            yylval.val.typ = INTVAL;
                            
                            return(CONSTANT); 
                        }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 85 "ansic.l"
{   yylval.val.ival = atol(yytext);
                            yylval.val.typ = INTVAL; 

                            return(CONSTANT); 
                        }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 91 "ansic.l"
{   yylval.val.dval = atof(yytext);
                            yylval.val.typ = DOUBLEVAL;

                            return(CONSTANT); 
                        }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 97 "ansic.l"
{   yylval.val.dval = atof(yytext);
                            yylval.val.typ = DOUBLEVAL;

                            return(CONSTANT); 
                        }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 103 "ansic.l"
{   yylval.val.dval = atof(yytext);
                            yylval.val.typ = DOUBLEVAL;

                            return(CONSTANT); 
                        }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 109 "ansic.l"
{   buffer = malloc(1);
                            buffer_size = 1; 
                            strcpy(buffer,""); 
                            BEGIN(INSTRING);
                        }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 115 "ansic.l"
{   buffer = malloc(1);
                            buffer_size = 1; 
                            strcpy(buffer,""); 
                            BEGIN(INCHAR);
                        }
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 121 "ansic.l"
{   yyerror("Unterminates character or string literal");
                            free(buffer);
                            BEGIN(INITIAL);
                        }
	YY_BREAK
case YY_STATE_EOF(INSTRING):
case YY_STATE_EOF(INCHAR):
#line 126 "ansic.l"
{   yyerror("EOF in string");
                            free(buffer);
                            BEGIN(INITIAL);
                        }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 131 "ansic.l"
{buffer = realloc(buffer,buffer_size+yyleng+1);
                            buffer_size += yyleng;
                            strcat(buffer,yytext);
                            if(YY_START==INCHAR && buffer_size>2)
                                yyerror("Illegal length of character literal");
                            }
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 137 "ansic.l"
/*Ignore this*/
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 139 "ansic.l"
{  int temp = 0, loop = 0;
                            for(loop=yyleng-2; loop>0; loop--){
                                temp <<= 4;
                                temp += hextoint(toupper(yytext[yyleng-loop]));
                            }
                            buffer = realloc(buffer,buffer_size+1);
                            buffer[buffer_size-1] = temp;
                            buffer[buffer_size] = '\0';
                            buffer_size += 1;
                            if(YY_START==INCHAR && buffer_size>2)
                                yyerror("Illegal length of character literal");
                            }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 152 "ansic.l"
{  int temp = 0, loop = 0;
                            for(loop=yyleng-1; loop>0; loop--){
                                temp <<= 3;
                                temp += (yytext[yyleng-loop] - '0');
                            }
                            buffer = realloc(buffer,buffer_size+1);
                            buffer[buffer_size-1] = temp;
                            buffer[buffer_size] = '\0';
                            buffer_size += 1;
                            if(YY_START==INCHAR && buffer_size>2)
                                yyerror("Illegal length of character literal");
                            }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 165 "ansic.l"
{  buffer = realloc(buffer, buffer_size+1);
                            switch(yytext[yyleng-1]){
                                case 'b' : buffer[buffer_size-1] = '\b'; break;
                                case 't' : buffer[buffer_size-1] = '\t'; break;
                                case 'n' : buffer[buffer_size-1] = '\n'; break;
                                case 'v' : buffer[buffer_size-1] = '\v'; break;
                                case 'f' : buffer[buffer_size-1] = '\f'; break;
                                case 'r' : buffer[buffer_size-1] = '\r'; break;
                                default  : buffer[buffer_size-1] = yytext[yyleng-1]; 
                            }
                            buffer[buffer_size] = '\0';
                            buffer_size += 1;
                            if(YY_START==INCHAR && buffer_size>2)
                                yyerror("Illegal length of character literal");
                        }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 181 "ansic.l"
{   if(YY_START==INSTRING){
                                yylval.str = buffer;
                                BEGIN(INITIAL);
                                return(STRING_LITERAL);
                            }
                            buffer = realloc(buffer,buffer_size+yyleng+1);
                            buffer_size += yyleng;
                            strcat(buffer,yytext);
                            if(buffer_size>2)
                                yyerror("Illegal length of character literal");
                        }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 193 "ansic.l"
{   if(YY_START==INCHAR){
                                yylval.val.cval = buffer[0];
                                if(buffer_size>2)
                                    yyerror("Illegal length of character literal");
                                yylval.val.typ = CHARVAL;

                                free(buffer);
                                BEGIN(INITIAL);
                                return(CONSTANT);
                            }
                            buffer = realloc(buffer,buffer_size+yyleng+1);
                            buffer_size += yyleng;
                            strcat(buffer,yytext);
                        }    
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 209 "ansic.l"
{   return(ELLIPSIS); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 210 "ansic.l"
{   return(RIGHT_ASSIGN); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 211 "ansic.l"
{   return(LEFT_ASSIGN); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 212 "ansic.l"
{   return(ADD_ASSIGN); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 213 "ansic.l"
{   return(SUB_ASSIGN); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 214 "ansic.l"
{   return(MUL_ASSIGN); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 215 "ansic.l"
{   return(DIV_ASSIGN); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 216 "ansic.l"
{   return(MOD_ASSIGN); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 217 "ansic.l"
{   return(AND_ASSIGN); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 218 "ansic.l"
{   return(XOR_ASSIGN); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 219 "ansic.l"
{   return(OR_ASSIGN); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 220 "ansic.l"
{   return(RIGHT_OP); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 221 "ansic.l"
{   return(LEFT_OP); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 222 "ansic.l"
{   return(INC_OP); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 223 "ansic.l"
{   return(DEC_OP); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 224 "ansic.l"
{   return(PTR_OP); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 225 "ansic.l"
{   return(AND_OP); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 226 "ansic.l"
{   return(OR_OP); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 227 "ansic.l"
{   return(LE_OP); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 228 "ansic.l"
{   return(GE_OP); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 229 "ansic.l"
{   return(EQ_OP); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 230 "ansic.l"
{   return(NE_OP); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 231 "ansic.l"
{   return(';'); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 232 "ansic.l"
{   return('{'); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 233 "ansic.l"
{   return('}'); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 234 "ansic.l"
{   return(','); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 235 "ansic.l"
{   return(':'); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 236 "ansic.l"
{   return('='); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 237 "ansic.l"
{   return('('); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 238 "ansic.l"
{   return(')'); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 239 "ansic.l"
{   return('['); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 240 "ansic.l"
{   return(']'); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 241 "ansic.l"
{   return('.'); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 242 "ansic.l"
{   return('&'); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 243 "ansic.l"
{   return('!'); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 244 "ansic.l"
{   return('~'); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 245 "ansic.l"
{   return('-'); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 246 "ansic.l"
{   return('+'); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 247 "ansic.l"
{   return('*'); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 248 "ansic.l"
{   return('/'); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 249 "ansic.l"
{   return('%'); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 250 "ansic.l"
{   return('<'); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 251 "ansic.l"
{   return('>'); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 252 "ansic.l"
{   return('^'); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 253 "ansic.l"
{   return('|'); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 254 "ansic.l"
{   return('?'); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 256 "ansic.l"
{
                }
	YY_BREAK
case 98:
/* rule 98 can match eol */
YY_RULE_SETUP
#line 258 "ansic.l"
{   yylloc.first_line++;
                    yylloc.first_column = yylloc.last_column = 0;
                }                
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 261 "ansic.l"
{ /* ignore bad characters */ }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 263 "ansic.l"
ECHO;
	YY_BREAK
#line 1409 "lex.yy.cc"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin.rdbuf();
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* The contents of this function are C++ specific, so the () macro is not used.
 * This constructor simply maintains backward compatibility.
 * DEPRECATED
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout ):
	yyin(arg_yyin ? arg_yyin->rdbuf() : std::cin.rdbuf()),
	yyout(arg_yyout ? arg_yyout->rdbuf() : std::cout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream& arg_yyin, std::ostream& arg_yyout ):
	yyin(arg_yyin.rdbuf()),
	yyout(arg_yyout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::ctor_common()
{
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = NULL;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	yyfree( yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yyfree( yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream& new_in, std::ostream& new_out )
{
	// was if( new_in )
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );

	// was if( new_out )
	yyout.rdbuf(new_out.rdbuf());
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if( ! new_in ) {
		new_in = &yyin;
	}

	if ( ! new_out ) {
		new_out = &yyout;
	}

	switch_streams(*new_in, *new_out);
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin.eof() || yyin.fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin.get( buf[0] );

	if ( yyin.eof() )
		return 0;

	if ( yyin.bad() )
		return -1;

	return 1;

#else
	(void) yyin.read( buf, max_size );

	if ( yyin.bad() )
		return -1;
	else
		return yyin.gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout.write( buf, size );
}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
int yyFlexLexer::yy_get_next_buffer()
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    yy_state_type yyFlexLexer::yy_get_previous_state()
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 254 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 254 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 253);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
    void yyFlexLexer::yyunput( int c, char* yy_bp)
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
#endif

    int yyFlexLexer::yyinput()
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyFlexLexer::yyrestart( std::istream& input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Delegate to the new version that takes an istream reference.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyFlexLexer::yyrestart( std::istream* input_file )
{
	if( ! input_file ) {
		input_file = &yyin;
	}
	yyrestart( *input_file );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

    void yyFlexLexer::yy_load_buffer_state()
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin.rdbuf(YY_CURRENT_BUFFER_LVALUE->yy_input_file);
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream& file, int size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Delegate creation of buffers to the new version that takes an istream reference.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
	YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	return yy_create_buffer( *file, size );
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream& file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file.rdbuf();
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 0;
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yyFlexLexer::yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
void yyFlexLexer::yyensure_buffer_stack(void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

    void yyFlexLexer::yy_push_state( int _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    void yyFlexLexer::yy_pop_state()
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    int yyFlexLexer::yy_top_state()
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError( const char* msg )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 263 "ansic.l"


int yywrap()
{
	return(1);
}

void yyerror(char *message){
    printf("\nError: %s at line %d clumn %d\n",message, yylloc.first_line+1, yylloc.first_column+1);
    exit(1);
}

void comment()
{
	char c, c1;

loop:
	while ((c = input()) != '*' && c != 0)
		if(c=='\n'){
            yylloc.first_line++;
            yylloc.first_column = 0;
        }

	if ((c1 = input()) != '/' && c != 0)
	{
		unput(c1);
		goto loop;
	}

	if (c != 0 && c=='\n'){
        yylloc.first_line++;
        yylloc.first_column = 0;
    }
}


int check_type()
{
/*
* pseudo code --- this is what it should check
*
*	if (yytext == type_name)
*		return(TYPE_NAME);
*
*	return(IDENTIFIER);
*/

/*
*	it actually will only return IDENTIFIER
*/

	return(IDENTIFIER);
}

void printchr(char c){
    if(c == '\a'){
        printf("\\a");
    }
    else if(c == '\b'){
        printf("\\b");
    }
    else if(c == '\f'){
        printf("\\f");
    }
    else if(c == '\n'){
        printf("\\n");
    }
    else if(c == '\r'){
        printf("\\r");
    }
    else if(c == '\t'){
        printf("\\t");
    }
    else if(c == '\v'){
        printf("\\v");
    }
    else
        printf("%c",c);
}

void printstr(char *str){
    char c;
    while((c = *str++) != '\0'){
        printchr(c);
    }
}

char *stoken[] = {
    "IDENTIFIER",
    "CONSTANT",
    "STRING_LITERAL",
    "SIZEOF",
    "PTR_OP",
    "INC_OP",
    "DEC_OP",
    "LEFT_OP",
    "RIGHT_OP",
    "LE_OP",
    "GE_OP",
    "EQ_OP",
    "NE_OP",
    "AND_OP",
    "OR_OP",
    "MUL_ASSIGN",
    "DIV_ASSIGN",
    "MOD_ASSIGN",
    "ADD_ASSIGN",
    "SUB_ASSIGN",
    "LEFT_ASSIGN",
    "RIGHT_ASSIGN",
    "AND_ASSIGN",
    "XOR_ASSIGN",
    "OR_ASSIGN",
    "TYPE_NAME",
    "TYPEDEF",
    "EXTERN",
    "STATIC",
    "AUTO",
    "REGISTER",
    "CHAR",
    "SHORT",
    "INT",
    "LONG",
    "SIGNED",
    "UNSIGNED",
    "FLOAT",
    "DOUBLE",
    "CONST",
    "VOLATILE",
    "VOID",
    "STRUCT",
    "UNION",
    "ENUM",
    "ELLIPSIS",
    "CASE",
    "DEFAULT",
    "IF",
    "ELSE",
    "SWITCH",
    "WHILE",
    "DO",
    "FOR",
    "GOTO",
    "CONTINUE",
    "BREAK",
    "RETURN"
};

